package tiktok

import "encoding/json"

type Response struct {
	Code      int             `json:"code"`
	Message   string          `json:"message"`
	RequestID string          `json:"request_id"`
	Data      json.RawMessage `json:"data"`
}

type AccessTokenResponse struct {
	AccessToken          string `json:"access_token"`
	AccessTokenExpireIn  int    `json:"access_token_expire_in"`
	RefreshToken         string `json:"refresh_token"`
	RefreshTokenExpireIn int    `json:"refresh_token_expire_in"`
	OpenID               string `json:"open_id"`
	SellerName           string `json:"seller_name"`
}

/*
type OrdersIDRequest struct {
	OrderID string `json:"order_id" url:"order_id" validate:"required"`
}

type AutoGenerated struct {
	Code      int      `json:"code"`
	Message   string   `json:"message"`
	RequestID string   `json:"request_id"`
	Data      struct{} `json:"data"`
}


type ProductSKU struct {
	ID              string           `json:"id"`
	SellerSku       string           `json:"seller_sku"`
	SalesAttributes []SalesAttribute `json:"sales_attributes"`
}

type SizeChart struct {
	Height       int    `json:"height"`
	ID           string `json:"id"`
	ThumbUrlList string `json:"thumb_url_list"`
	UrlList      string `json:"url_list"`
	Width        int    `json:"width"`
}
*/
