# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - go test -v -race -timeout 10m -covermode atomic -coverprofile=coverage.txt -cover ./...
      - go tool cover -func coverage.txt

  integration:
    cmds:
      - go test -v -race -timeout 10m -tags integration -covermode atomic -coverprofile=coverage.txt -cover -failfast ./...
      - go tool cover -func coverage.txt
